name: fbclone-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api
    container_name: fbclone-frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api
      INTERNAL_API_BASE_URL: http://host.docker.internal:3001/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    restart: unless-stopped
